[metadata]
name = asn1docs
version = 0.0.1
author = Q Misell
author_email = qmisell@mpi-inf.mpg.de
description = Compile ASN.1 modules into HTML documentation.
license_file = LICENSE.md
url = https://github.com/TheEnbyperor/asn1docs
project_urls =
    Bug Tracker = https://github.com/TheEnbyperor/asn1docs/issues

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.11
install_requires =
    pyparsing
    jinja2
    markdown-it-py

[options.packages.find]
where = src

[options.package_data]
asn1docs =
    templates/**